### ISSUE TITLE
NVIDIA CUDA Environment

### ISSUE THREAD

**Issue by caglarmert** [caglarmert/MOT-Research#11]
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 41, in get_extensions
    raise NotImplementedError('Cuda is not availabel')
NotImplementedError: Cuda is not availabel

**Comment by caglarmert** [comment]
Manually installing CUDA 10.0 with CuDNN 7.5.2 and 411 driver
I have disabled-
GeForce Experience Software (had already installed newer version)
GeForce Drivers (had already installed newer version)
PhysX (had already installed newer version)
Visual Studio Integration.
